# -*- coding: utf-8 -*-
"""streamlit_app.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19DYEPPY_ln06912H9aSAN-1QCzY7sGSg

https://blog.streamlit.io/langchain-tutorial-4-build-an-ask-the-doc-app/

https://blog.streamlit.io/langchain-tutorial-1-build-an-llm-powered-app-in-18-lines-of-code/
"""

pip install streamlit langchain openai tiktoken

import streamlit as st
from langchain.llms import OpenAI

st.title('Quickstart App')

openai_api_key = st.sidebar.text_input("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")

def generate_response(input_text):
  llm = OpenAI(temperature=0.7, openai_api_key=openai_api_key)
  st.info(llm(input_text))

with st.form('my_form'):
  text = st.text_area('Enter text:', 'What are the three key pieces of advice for learning how to code?')
  submitted = st.form_submit_button('Submit')
  if not openai_api_key.startswith('sk-'):
    st.warning('Please enter your OpenAI API key!', icon='⚠')
  if submitted and openai_api_key.startswith('sk-'):
    generate_response(text)

